_wandb:
    value:
        cli_version: 0.23.1
        e:
            95apj3g2nvj2eobn1n3mbiubjajzu27q:
                args:
                    - --csv
                    - Motion_Normalized_Dataset.csv
                    - --hidden
                    - 512,256,128
                    - --epochs
                    - "300"
                codePath: train_ann.py
                codePathLocal: train_ann.py
                cpu_count: 24
                cpu_count_logical: 32
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "1964618686464"
                        used: "1335149801472"
                email: r13922a13@ntu.edu.tw
                executable: /home/andy/anaconda3/envs/gesture-ann/bin/python
                git:
                    commit: a446583fb3491bd9121f78220674419b7af15410
                    remote: https://github.com/sergiuoprea/Hand-Gesture-Recognition-Datasets
                gpu: NVIDIA GeForce RTX 4090
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 16384
                      memoryTotal: "25757220864"
                      name: NVIDIA GeForce RTX 4090
                      uuid: GPU-0b153029-c66c-fd31-f559-95d08426d1a4
                host: 140.112.31.164
                memory:
                    total: "134822002688"
                os: Linux-6.14.0-37-generic-x86_64-with-glibc2.39
                program: /home/andy/mycode/Hand-Gesture-Recognition-Datasets/train_ann.py
                python: CPython 3.10.19
                root: /home/andy/mycode/Hand-Gesture-Recognition-Datasets
                startedAt: "2025-12-23T07:55:56.861756Z"
                writerId: 95apj3g2nvj2eobn1n3mbiubjajzu27q
        m: []
        python_version: 3.10.19
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 16
            "4": 3.10.19
            "5": 0.23.1
            "12": 0.23.1
            "13": linux-x86_64
batch_size:
    value: 32
csv:
    value: Motion_Normalized_Dataset.csv
device:
    value: cuda
dropout:
    value: 0.2
epochs:
    value: 300
hidden:
    value:
        - 512
        - 256
        - 128
lr:
    value: 0.001
seed:
    value: 42
test_frac:
    value: 0.15
val_frac:
    value: 0.15
weight_decay:
    value: 0.0001
